[package]
name = "kvs-client"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "0.12"
prost = "0.13"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1"
clap = { version = "4.5", features = ["derive"] }

[build-dependencies]
tonic-build = "0.12"
